# Generated by Django 4.2 on 2024-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqe_id', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=30)),
                ('url', models.TextField()),
            ],
        ),
    ]
