# Generated by Django 4.2 on 2024-07-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_person_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
    ]
