# Generated by Django 4.2 on 2024-07-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_person_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
    ]
