# Generated by Django 4.2 on 2024-07-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_person_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company',
        ),
    ]
